In [ ]:
#Following File has different Models applied on Dataset such as Decision Tree and other Ensemble Models

In [ ]:
#In this case study we will be applying different models to check the best accuracy_score 

#APPROACHES FOR ANY PROJECT
    ##1) Build multiple individual models --> Select the best on accuracy
    ##2) ENSEMBLE MODDELLING-->Running multiple models together 
      
##Base DT-->Accuracy-99.22%
##Tuned DT--->min_samples_leaf=5, max_depth=10-->Accuracy-94.21%
##Base SVM-SVC-->Accuracy-85.55%
##Tuned SVM-SVC--->COST=50-->Accuracy-99.61%
##Logistic_Regg-->Accuracy-69.94%
##ExtraTreesClassifier-->Accuracy-98.44%
##Random_Forest_Classifier-->Accuracy-98.26%
##AdaBoostClassifier-->Accuracy obtained- 98.45%
##Gradient_Boosting_Classifier-->Accuracy obtained= 99.80%
##ENSEMBLE MODELLING

### IMPORT DEPENDENCIES 

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns",None)

In [ ]:
## Import data in dataframe

In [9]:
cars_data=pd.read_csv("cars.csv",header=None) ##header=None since we dont have headers

In [10]:
cars_data.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [11]:
## Checking the number of rows and columns
cars_data.shape


(1728, 7)

In [12]:
## Checking if null values present
cars_data.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [13]:
## Checking the datatype of variables
cars_data.dtypes

0    object
1    object
2    object
3    object
4    object
5    object
6    object
dtype: object

In [14]:
## Assigning column headers
cars_data.columns=['buying','maint','doors','persons','lug_boot','safety','classes']

In [15]:
cars_data.head()

buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc

In [16]:
##Creating copy of data

cars_df=pd.DataFrame.copy(cars_data) 

In [17]:
##Storing all the columns of cars_df in column for further transformation
colname=cars_df.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [18]:
##Conversion of categorical data to numerical using LabelEncoder 

from sklearn import preprocessing
colname=['buying','maint','doors','persons','lug_boot','safety','classes']
 
le=preprocessing.LabelEncoder()

for x in colname:
    cars_df[x]=le.fit_transform(cars_df[x]) ##fit and transform function combined together
    ##Fit trains the scaler object for the range of scales
    ##Transform maps the variable (Eg Age) to the specific range of scales given by the fit

In [19]:
cars_df.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       3      3      0        0         2       1        2
1       3      3      0        0         2       2        2
2       3      3      0        0         2       0        2
3       3      3      0        0         1       1        2
4       3      3      0        0         1       2        2

In [20]:
cars_data.classes.value_counts()
##acc==>0
##good==>1
##unacc==>2
##vgood==>3


unacc    1210
acc       384
good       69
vgood      65
Name: classes, dtype: int64

In [21]:
#Creating X and Y 
#Here we are splitting the train data since we have single file
X=cars_df.values[:,:-1]
Y=cars_df.values[:,-1]
Y=Y.astype(int)

In [22]:
##Benefit of scaling is it reduces the discripancy in data due to difference in the range of variables
##it converts the variables in range of -3 to +3
##Here the data has minimum difference so we can skip scaling but it is good practice
##Age and Sallary examples

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

##Fit and transform performed separately
scaler.fit(X)
##Fit function decides the scales to fit to input X values

X=scaler.transform(X)
##transform maps these new ranges decided by fit function to the input values of X
print(X)

[[ 1.34164079  1.34164079 -1.34164079 -1.22474487  1.22474487  0.        ]
 [ 1.34164079  1.34164079 -1.34164079 -1.22474487  1.22474487  1.22474487]
 [ 1.34164079  1.34164079 -1.34164079 -1.22474487  1.22474487 -1.22474487]
 ...
 [-0.4472136  -0.4472136   1.34164079  1.22474487 -1.22474487  0.        ]
 [-0.4472136  -0.4472136   1.34164079  1.22474487 -1.22474487  1.22474487]
 [-0.4472136  -0.4472136   1.34164079  1.22474487 -1.22474487 -1.22474487]]


In [23]:
##Converting in Train and Test
##random_state to get same output
##random_state in kaggle is mostle 42
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)

In [ ]:
## MODEL BUILDING

### DECISION TREE MODEL

In [37]:
##Model building using DT
##Accuracy here is 0.99 which is better than pruning the DT
from sklearn.tree import DecisionTreeClassifier

##Creating model object
model_DT=DecisionTreeClassifier(criterion="gini",random_state=10)
##random_state is also given here coz in DT while in different iteration it can generated 
##same values for Two iteration to prevent it 



##Train the model
model_DT.fit(X_train,Y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=10,
            splitter='best')

In [33]:
##Pruning done here 
##But pruning gave us less accuracy of 0.9421 which is reduced from previous
##Therefore avoid unnecessary prunning
from sklearn.tree import DecisionTreeClassifier

##Creating model object
model_DT=DecisionTreeClassifier(criterion="gini",min_samples_leaf=5, max_depth=10, random_state=10)
##random_state is also given here coz in DT while in different iteration it can generated 
##same values for Two iteration to prevent it 



##Train the model
model_DT.fit(X_train,Y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=10,
            splitter='best')

In [ ]:
##DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
##            max_features=None-->(specifies the num of variables), max_leaf_nodes=None-->(specifies the dept of tree),
##            min_impurity_decrease=0.0, min_impurity_split=None,
##            min_samples_leaf=1, min_samples_split=2,
##            min_weight_fraction_leaf=0.0, presort=False, random_state=10,
##            splitter='best')

In [38]:
##Prediction
Y_pred=model_DT.predict(X_test)
Y_pred

array([2, 2, 2, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3,
       2, 0, 2, 2, 2, 2, 2, 0, 1, 3, 1, 2, 0, 2, 0, 2, 2, 2, 2, 3, 2, 2,
       0, 0, 2, 2, 3, 2, 2, 2, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 3, 2, 2, 0, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 1, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 3, 2, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 0, 2, 1, 0, 2, 2, 2, 2, 0, 3, 0, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 3, 0, 2, 2, 2, 3, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 2, 0,
       2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2,
       2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 0, 2, 2, 0, 3, 3, 0, 2,
       0, 2, 2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2,

In [39]:
##Zipping og values with predicted values
print(list(zip(Y_test,Y_pred)))

[(2, 2), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (1, 1), (3, 3), (1, 1), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (3, 3), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (0, 0), (3, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0),

In [40]:
###Model Evaluation
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))

##Overfitted - is when accuracy is high on train data n less on test data
##In our case we have good accuracy on test data so it is not overfitted 
##Only 4 misclassification therefore we have got good model

[[101   0   1   0]
 [  2  19   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]
0.9922928709055877
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       102
           1       1.00      0.90      0.95        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

   micro avg       0.99      0.99      0.99       519
   macro avg       0.99      0.96      0.98       519
weighted avg       0.99      0.99      0.99       519



In [31]:
##DT is good for data exploration and it helps to find significant variables
#This called feature selection using DecisionTree.feature_importances_
##The output given has summation of all values = 1
##If any varible giving value 0 or near to 0 then we can eliminate that variable since it is insignificant
##We zip it with column name for proper understanding of corresponding respective values

print(list(zip(colname,model_DT.feature_importances_)))

[('buying', 0.1510848831946676), ('maint', 0.2506508516803624), ('doors', 0.060026331736828115), ('persons', 0.19355707150872045), ('lug_boot', 0.09892620952419463), ('safety', 0.2457546523552268)]


In [32]:

from sklearn import tree
with open("model_DecisionTree.txt", "w") as f:  #Opening new file to store logs of DT performed 
    
    f = tree.export_graphviz(model_DT, feature_names=colname[:-1],
                             out_file=f)
    
#generate the file and upload the code in webgraphviz.com to plot the decision tree

### SVM Model

In [41]:
##Using SVM for Classification
##Accuracy obtained= 0.855
##Creating model object and defining kernel,gamma,cost
from sklearn import svm
classifier=svm.SVC(kernel="rbf", C=1.0, gamma=0.1) 
classifier.fit(X_train,Y_train)     ##Training the model for givenX-train on Y-train
Y_pred=classifier.predict(X_test)   ##Testing the model and predicting values on the X_test
print(list(Y_pred))

[2, 2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 3, 0, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 3, 2, 2, 2, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2, 0, 3, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 2, 0, 0, 2, 0, 3, 0, 0, 0, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 

In [42]:
###Model Evaluation for SVM
##Accuracy obtained= 0.855
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))


[[ 82   0  20   0]
 [ 21   0   0   0]
 [ 17   0 354   0]
 [ 17   0   0   8]]
0.8554913294797688
              precision    recall  f1-score   support

           0       0.60      0.80      0.69       102
           1       0.00      0.00      0.00        21
           2       0.95      0.95      0.95       371
           3       1.00      0.32      0.48        25

   micro avg       0.86      0.86      0.86       519
   macro avg       0.64      0.52      0.53       519
weighted avg       0.84      0.86      0.84       519



### TUNNED SVM

In [43]:
##Tuning the SVM for Classification, Cost=50
##Accuracy obtained= 99.61%
from sklearn import svm
classifier=svm.SVC(kernel="rbf", C=50, gamma=0.1) ##Creating model object and defining kernel,gamma,cost
classifier.fit(X_train,Y_train)     ##Training the model for givenX-train on Y-train
Y_pred=classifier.predict(X_test)   ##Testing the model and predicting values on the X_test
print(list(Y_pred))

[2, 2, 2, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3, 2, 0, 2, 2, 2, 2, 2, 0, 1, 3, 1, 2, 0, 2, 0, 2, 2, 2, 2, 3, 2, 2, 0, 0, 2, 2, 3, 2, 2, 2, 1, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 3, 2, 2, 0, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 1, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 3, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 0, 2, 1, 0, 2, 2, 2, 2, 0, 3, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 3, 0, 2, 2, 2, 3, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 0, 0, 2, 0, 3, 3, 0, 2, 0, 2, 2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 2, 0, 2, 

In [44]:
###Model Evaluation for tuned SVM
##Accuracy obtained= 99.61%
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))


[[100   1   1   0]
 [  0  21   0   0]
 [  0   0 371   0]
 [  0   0   0  25]]
0.9961464354527938
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       102
           1       0.95      1.00      0.98        21
           2       1.00      1.00      1.00       371
           3       1.00      1.00      1.00        25

   micro avg       1.00      1.00      1.00       519
   macro avg       0.99      1.00      0.99       519
weighted avg       1.00      1.00      1.00       519



### LOGISTIC REGRESSION Model

In [45]:
###Model building Using Logistics
##This gives very less accxuracy since Logistic is not suitable for multiclass classification
##Logistic is used for Binary classification

from sklearn.linear_model import LogisticRegression
#Create a model object
classifier=LogisticRegression()

#Fitting training data to the model (Teaching the model)
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

print(classifier.coef_)
print(classifier.intercept_)

[[-0.09230671 -0.11539674  0.05626011  0.84486111 -0.18405585 -0.20809847]
 [-0.11297022 -0.17447885  0.15426829  0.66646756 -0.09553846  0.30990112]
 [ 0.12775175  0.1926193  -0.13839202 -1.03465424  0.34314596  0.35409774]
 [-0.09543798 -0.22959436  0.30718016  0.81859709 -0.86092515 -1.77535646]]
[-1.39923095 -3.38368125  1.06766105 -5.00633204]


In [46]:
###Model Evaluation Logistic Regression
##Accuracy obtained= 0.699 , lowest accuracy
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))


[[ 22   0  80   0]
 [  3   0  18   0]
 [ 30   0 341   0]
 [ 11   0  14   0]]
0.6994219653179191
              precision    recall  f1-score   support

           0       0.33      0.22      0.26       102
           1       0.00      0.00      0.00        21
           2       0.75      0.92      0.83       371
           3       0.00      0.00      0.00        25

   micro avg       0.70      0.70      0.70       519
   macro avg       0.27      0.28      0.27       519
weighted avg       0.60      0.70      0.64       519



### Bagging_Classifier ExtraTreesClassifier

In [ ]:
#predicting using the Bagging_Classifier ExtraTreesClassifier
##Accuracy obtained= 98.44%
from sklearn.ensemble import ExtraTreesClassifier
 
model=ExtraTreesClassifier(100,random_state=10)
#fit the model on the data and predict the values
model=model.fit(X_train,Y_train)
 
Y_pred=model.predict(X_test)
 
 

 


In [49]:
###Model Evaluation for ExtraTreesClassifier
##Accuracy obtained= 98.44
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))


[[101   1   0   0]
 [  3  18   0   0]
 [  1   0 370   0]
 [  1   2   0  22]]
0.9845857418111753
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       102
           1       0.86      0.86      0.86        21
           2       1.00      1.00      1.00       371
           3       1.00      0.88      0.94        25

   micro avg       0.98      0.98      0.98       519
   macro avg       0.95      0.93      0.94       519
weighted avg       0.98      0.98      0.98       519



### Random_Forest_Classifier

In [50]:
#predicting using the Random_Forest_Classifier
##Accuracy obtained= 98.26
from sklearn.ensemble import RandomForestClassifier
 
model_RandomForest=RandomForestClassifier(n_estimators=101,random_state=10)
 
#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)
 
Y_pred=model_RandomForest.predict(X_test)

In [51]:
###Model Evaluation for RANDOM FOREST
##Accuracy obtained= 98.26
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))


[[ 99   3   0   0]
 [  1  19   0   1]
 [  2   0 369   0]
 [  2   0   0  23]]
0.9826589595375722
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       102
           1       0.86      0.90      0.88        21
           2       1.00      0.99      1.00       371
           3       0.96      0.92      0.94        25

   micro avg       0.98      0.98      0.98       519
   macro avg       0.94      0.95      0.95       519
weighted avg       0.98      0.98      0.98       519



### AdaBoost_Classifier

In [53]:
#predicting using the AdaBoost_Classifier
from sklearn.ensemble import AdaBoostClassifier
 
model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(),
                                  n_estimators=10, #default n_estimators=50
                                  random_state=10)
#fit the model on the data and predict the values
model_AdaBoost.fit(X_train,Y_train)
Y_pred=model_AdaBoost.predict(X_test)
 

 


In [54]:
###Model Evaluation for AdaBoostClassifier
##Accuracy obtained= 98.45
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))

[[ 99   2   1   0]
 [  4  17   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]
0.9845857418111753
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       102
           1       0.89      0.81      0.85        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

   micro avg       0.98      0.98      0.98       519
   macro avg       0.96      0.94      0.95       519
weighted avg       0.98      0.98      0.98       519



### Gradient_Boosting_Classifier

In [55]:
#predicting using the Gradient_Boosting_Classifier
from sklearn.ensemble import GradientBoostingClassifier
 
model_GradientBoosting=GradientBoostingClassifier(n_estimators=270, #default n_estimators=100
                                                  random_state=10)
 
#fit the model on the data and predict the values
model_GradientBoosting.fit(X_train,Y_train)
 
Y_pred=model_GradientBoosting.predict(X_test)

In [56]:
###Model Evaluation for Gradient_Boosting_Classifier
##Accuracy obtained= 99.80
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))

[[101   1   0   0]
 [  0  21   0   0]
 [  0   0 371   0]
 [  0   0   0  25]]
0.9980732177263969
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       102
           1       0.95      1.00      0.98        21
           2       1.00      1.00      1.00       371
           3       1.00      1.00      1.00        25

   micro avg       1.00      1.00      1.00       519
   macro avg       0.99      1.00      0.99       519
weighted avg       1.00      1.00      1.00       519



### ENSEMBLE MODELLING

In [62]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier ##Creatin this ensembled model
from sklearn.neighbors import KNeighborsClassifier
 
# create the sub models
estimators = []
#model1 = LogisticRegression()
#estimators.append(('log', model1)) ##log for logistic , it can be any name
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('cart', model2))
model3 = SVC(kernel="rbf", C=50,gamma=0.1)
estimators.append(('svm', model3))
#model4 = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
#estimators.append(('knn', model4))
 
    
# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)

In [63]:
###Model Evaluation for ENSEMBLE MODELLING
##Accuracy obtained= 98.45 with logistic regg
##Accuracy obtained= 99.42 after removing Logistic regg
##Accuracy obtained= 99.42 after removing KNN
##We get average accuracy of 99.42 from base DT() and SVC(99.61) in ensemble modelling
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))

[[102   0   0   0]
 [  2  19   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]
0.9942196531791907
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       102
           1       1.00      0.90      0.95        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

   micro avg       0.99      0.99      0.99       519
   macro avg       0.99      0.97      0.98       519
weighted avg       0.99      0.99      0.99       519

